//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IQueueService")]
public interface IQueueService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/Push", ReplyAction="http://tempuri.org/IQueueService/PushResponse")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    void Push(string aggregateId, int version, object e);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/TryGetNext", ReplyAction="http://tempuri.org/IQueueService/TryGetNextResponse")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    bool TryGetNext(out object next, string aggregateId, int version);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueueService/GetAllNext", ReplyAction="http://tempuri.org/IQueueService/GetAllNextResponse")]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
    object[] GetAllNext(string aggregateId, int version);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IQueueServiceChannel : IQueueService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class QueueServiceClient : System.ServiceModel.ClientBase<IQueueService>, IQueueService
{
    
    public QueueServiceClient()
    {
    }
    
    public QueueServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public QueueServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public QueueServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public QueueServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void Push(string aggregateId, int version, object e)
    {
        base.Channel.Push(aggregateId, version, e);
    }
    
    public bool TryGetNext(out object next, string aggregateId, int version)
    {
        return base.Channel.TryGetNext(out next, aggregateId, version);
    }
    
    public object[] GetAllNext(string aggregateId, int version)
    {
        return base.Channel.GetAllNext(aggregateId, version);
    }
}
